# Generated by Django 3.2.6 on 2021-08-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="backup",
            name="error_logs",
            field=models.TextField(blank=True, null=True),
        ),
    ]
