repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-json
      - id: check-ast
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files", "--skip-gitignore"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--max-line-length", "120"]
  - repo: https://github.com/pycqa/pylint/
    rev: v2.13.4
    hooks:
    - id: pylint
      args: [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
  - repo: https://github.com/PyCQA/prospector
    rev: 1.7.5
    hooks:
    - id: prospector
      args:
      - --summary-only
