# Generated by Django 3.1.3 on 2020-11-07 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=250)),
                ('ssl_key', models.FileField(upload_to='ssh_keys')),
                ('active_to_backup', models.BooleanField(default=True)),
                ('active_to_retore', models.BooleanField(default=True)),
                ('storage_type', models.CharField(choices=[('AMS3', 'Amazon S3'), ('ACLD', 'Apache Libcloud'), ('ASTG', 'Azure Storage'), ('DGON', 'Digital Ocean'), ('DRPB', 'Dropbox'), ('FTP', 'Ftp'), ('GCTG', 'Google Cloud Storage'), ('SFTP', 'Sftp')], max_length=5)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('host', models.CharField(max_length=250)),
                ('connect_username', models.CharField(default='ubuntu', max_length=150)),
                ('ssh_key', models.FileField(upload_to='ssh_keys')),
                ('ssh_key_pass', models.CharField(max_length=250)),
                ('databases', models.ManyToManyField(to='server.Database')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
