# Generated by Django 3.1.3 on 2020-11-24 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import server.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("server", "0009_auto_20201124_1718"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="server",
            name="ssh_key_pass",
        ),
        migrations.CreateModel(
            name="ConnectionKeys",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "key",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=server.models.user_ssh_keys_path,
                    ),
                ),
                ("key_pass", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "key_type",
                    models.CharField(
                        choices=[("SSH", "SSH"), ("SSL", "SSL")], max_length=5
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="database",
            name="ssl_key",
        ),
        migrations.RemoveField(
            model_name="server",
            name="ssh_key",
        ),
        migrations.AddField(
            model_name="database",
            name="ssl_key",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="server.connectionkeys",
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="ssh_key",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="server.connectionkeys",
            ),
        ),
    ]
