# Generated by Django 3.2.6 on 2021-08-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20201124_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadstorageconfig',
            options={'verbose_name_plural': 'Upload Storage Configs'},
        ),
        migrations.RemoveField(
            model_name='database',
            name='host',
        ),
        migrations.RemoveField(
            model_name='database',
            name='ssl_key',
        ),
    ]
