# Generated by Django 3.1.3 on 2020-11-07 12:27

import backup.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0008_auto_20201107_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('REQUEST', 'Request'), ('QUEUE', 'Queue'), ('CREATED', 'Created'), ('ERROR', 'Error')], default='REQUEST', max_length=10)),
                ('filename', models.FileField(upload_to=backup.models.user_directory_path)),
                ('database', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='server.database')),
                ('server', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='server.server')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
