# Generated by Django 3.1.3 on 2020-11-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20201107_1227'),
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.database'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.server'),
        ),
    ]
