# Generated by Django 3.2.6 on 2021-08-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_auto_20201107_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
