# Generated by Django 3.2.6 on 2021-08-15 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0013_auto_20210815_1312'),
        ('backup', '0003_backup_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoreJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('REQUEST', 'Request'), ('QUEUE', 'Queue'), ('CREATED', 'Created'), ('ERROR', 'Error')], default='REQUEST', max_length=10)),
                ('logs', models.TextField(blank=True, null=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup.backup')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.database')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.server')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
