# Generated by Django 3.2.6 on 2021-08-21 13:02

import backup.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0004_restorejob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='filename',
            field=models.FileField(blank=True, null=True, upload_to=backup.models.user_directory_path),
        ),
    ]
